Repository revoltchat/revite, pull requests merged in 2022-01, with the labels that each got.

#350 feat: make kick and ban red in the context menu
  src/lib/ContextMenus.tsx
Labels: fluff

#487 fix: Don't embed discovery links
  src/components/common/messaging/embed/EmbedInvite.tsx
Labels: improvement

#414 meta: add issue forms
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: meta

#493 feat(messaging): quick action bar
  src/components/common/messaging/Message.tsx
  src/components/common/messaging/MessageBase.tsx
  src/components/common/messaging/bars/MessageOverlayBar.tsx
Labels: enhancement
